nginx:
  build: ./nginx
  volumes:
    - ./client:/var/www/app
    - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    - ./nginx/error.log:/var/log/nginx/error.log
    - ./nginx/access.log:/var/log/nginx/access.log
  ports:
    - 8081:80
  tty: true
  